"""database updated

Revision ID: 113a3ef1a172
Revises: ad6e1774075a
Create Date: 2020-04-24 15:34:53.451370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '113a3ef1a172'
down_revision = 'ad6e1774075a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usersinfo', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersinfo', sa.Column('email', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###
