"""database updated

Revision ID: 3ab95ce7aa1b
Revises: 113a3ef1a172
Create Date: 2020-04-24 15:35:37.211471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab95ce7aa1b'
down_revision = '113a3ef1a172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usersinfo', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersinfo', sa.Column('email', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###
