"""update user_id column in user table

Revision ID: 69b3ecb7f1c5
Revises: eaa530d80273
Create Date: 2020-04-23 21:38:13.986467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69b3ecb7f1c5'
down_revision = 'eaa530d80273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.drop_column('users', 'id')
    # ### end Alembic commands ###
