"""blog image column added

Revision ID: 73e0b0b99e15
Revises: cf5f583511e8
Create Date: 2020-04-30 15:47:21.356893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73e0b0b99e15'
down_revision = 'cf5f583511e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('recipe_img', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'recipe_img')
    # ### end Alembic commands ###
