"""recipe_image changed to null

Revision ID: e13ce66efdd9
Revises: 73e0b0b99e15
Create Date: 2020-04-30 15:49:41.482172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13ce66efdd9'
down_revision = '73e0b0b99e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('recipe_img', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'recipe_img')
    # ### end Alembic commands ###
