"""database updated

Revision ID: eee07ca69633
Revises: 6db91fd04d5a
Create Date: 2020-04-24 15:40:13.561276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee07ca69633'
down_revision = '6db91fd04d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersinfo', sa.Column('email', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'usersinfo', 'users', ['email'], ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usersinfo', type_='foreignkey')
    op.drop_column('usersinfo', 'email')
    # ### end Alembic commands ###
